declare namespace Cloudflare {
  interface Env {
    DB: D1Database;
    ASSETS: Fetcher;
    YANDEX_DIRECT_OAUTH_TOKEN?: string;
    YANDEX_DIRECT_CLIENT_LOGIN?: string;
    YANDEX_DIRECT_CAMPAIGN_ID?: string;
    YANDEX_METRICA_OAUTH_TOKEN?: string;
    YANDEX_METRICA_COUNTER_ID?: string;
    YANDEX_METRICA_GOAL_ID?: string;
    YANDEX_WORDSTAT_OAUTH_TOKEN?: string;
    YANDEX_WORDSTAT_CLIENT_ID?: string;
    YANDEX_WORDSTAT_REGION_IDS?: string;
    YANDEX_WORDSTAT_REGION_NAMES?: string;
    YANDEX_WORDSTAT_DEVICE?: string;
    P0_WORDSTAT_BRIDGE_URL?: string;
    P0_WORDSTAT_BRIDGE_TOKEN?: string;
    P0_DESTINATION_BRIDGE_URL?: string;
    P0_DESTINATION_BRIDGE_TOKEN?: string;
    P0_FINANCIAL_INTELLIGENCE_BRIDGE_URL?: string;
    P0_FINANCIAL_INTELLIGENCE_BRIDGE_TOKEN?: string;
    P0_FIRST_PARTY_SITE_URL?: string;
    P0_E2E_FIXTURE_SCENARIO?: string;
    OPENAI_API_KEY?: string;
    P0_AGENT_MODEL?: string;
  }
}
